# Generated by Django 3.1.1 on 2020-10-09 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='age_covered',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='gender_covered',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dataset',
            name='income_covered',
            field=models.TextField(null=True),
        ),
    ]
