# Generated by Django 3.1.1 on 2020-10-09 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0003_dataset_columns_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='columns_name',
        ),
        migrations.AddField(
            model_name='dataset',
            name='columns_covered',
            field=models.TextField(null=True),
        ),
    ]
