# Generated by Django 3.1.1 on 2020-10-12 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0007_dataset_csv_len'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='information',
            field=models.TextField(default='summary'),
        ),
    ]
