# Generated by Django 3.1.1 on 2020-10-12 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0008_auto_20201012_1256'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dataset',
            old_name='csv_len',
            new_name='data_len',
        ),
    ]
