# Generated by Django 3.1.1 on 2020-10-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0010_remove_dataset_data_len'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dataset',
            name='age_covered',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='cities_covered',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='gender_covered',
        ),
        migrations.RemoveField(
            model_name='dataset',
            name='income_covered',
        ),
        migrations.AddField(
            model_name='dataset',
            name='name',
            field=models.TextField(default='Name'),
        ),
        migrations.AlterField(
            model_name='dataset',
            name='information',
            field=models.TextField(),
        ),
    ]
