# Generated by Django 3.1.1 on 2020-10-20 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datein', '0011_auto_20201020_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.TextField(),
        ),
    ]
